---
-
   name: Coleta informacao 
   hosts: all
   tasks: 

      - name: Coleta informacao fatos
        ansible.builtin.setup:
           filter:
              - 'ansible_distribution'
              - 'ansible_machine_id'
              - 'ansible_*_mb'
