---
-
   name: Coleta informacao 
   hosts: all
   tasks: 

      - name: Coleta informacao fatos
        ansible.builtin.setup:
           filter:
              - 'ansible_distribution'
              - 'ansible_machine_id'
              - 'ansible_*_mb'
              
      - name: Rede 
        ansible.builtin.debug:
          msg: Endereco IP  {{ ansible_all_ipv4_addresses }} - 
          
       - name: Sistema  
        ansible.builtin.debug:
          msg: |
          Arquitetura {{ ansible_architecture }}
          SO {{ ansible_distribution_file_variety }} 
          Release {{ ansible_distribution_release }} 
          Memoria {{ ansible_memory_mb }} 
          
          
          
          
        
