---
-
   name: Coleta informacao 
   hosts: all
   tasks: 

      - name: Coleta informacao fatos
        ansible.builtin.setup:
           filter:
              - 'ansible_distribution'
              - 'ansible_machine_id'
              - 'ansible_*_mb'
              
      - name: Teste 
        ansible.builtin.debug:
          msg: gateway {{ ansible_default_ipv4.gateway }}
        
