---
-
   name: Configura Mysql 
   hosts: all
   roles: 
     - name: Configura Mysql de forma segura
       role: ansible-role-mysql_secure_installation

   tasks: 

#teste

     - name: Start Mysql 
       service: 
          name: mysql
          state: started
          enabled: yes
          
